import type { Metadata } from "next";
import "@fontsource/apfel-grotezk"; // Defaults to weight 400
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="dark antialiased">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
